export const projects = [
  {
    title: 'Bistro grad',
    slug: 'bistro-grad',
    featuredImage: '/our-work/bistro-grad-our-work.png',
    listImage: '/our-work/bistro-grad-home.png',
    categories: ['social media', 'marketing'],
    backgroundColor: '#F286B7',
    textColor: '#000',
    ready: true,
  },
  {
    title: 'Prana',
    slug: 'prana',
    featuredImage: '/our-work/prana-our-work.png',
    listImage: '/our-work/prana-home.png',
    categories: ['branding', 'social media', 'marketing'],
    backgroundColor: '#FFF7EC',
    textColor: '#000',
    ready: true,
  },
  // {
  //   title: 'Roger Directors Agency',
  //   slug: 'roger-directors',
  //   featuredImage: '/our-work/roger-our-work.png',
  //   listImage: '/our-work/roger-home.png',
  //   categories: ['development'],
  //   backgroundColor: '#8eb8a3',
  //   textColor: '#000',
  //   ready: false,
  // },
  {
    title: 'ZLA ZLA',
    slug: 'zla-zla',
    featuredImage: '/our-work/zla-zla-our-work.jpg',
    listImage: '/our-work/zla-zla-home.jpg',
    categories: ['branding', 'social media', 'marketing'],
    backgroundColor: '#000',
    textColor: '#fff',
    ready: true,
  },
  {
    title: 'Bistro grad',
    slug: 'bistro-grad',
    featuredImage: '/our-work/bistro-grad-our-work.png',
    listImage: '/our-work/bistro-grad-home.png',
    categories: ['social media', 'marketing'],
    backgroundColor: '#F286B7',
    textColor: '#000',
    ready: true,
  },
  {
    title: 'Prana',
    slug: 'prana',
    featuredImage: '/our-work/prana-our-work.png',
    listImage: '/our-work/prana-home.png',
    categories: ['branding', 'social media', 'marketing'],
    backgroundColor: '#FFF7EC',
    textColor: '#000',
    ready: true,
  },
  // {
  //   title: 'Roger Directors Agency',
  //   slug: 'roger-directors',
  //   featuredImage: '/our-work/roger-our-work.png',
  //   listImage: '/our-work/roger-home.png',
  //   categories: ['development'],
  //   backgroundColor: '#8eb8a3',
  //   textColor: '#000',
  //   ready: false,
  // },
  {
    title: 'ZLA ZLA',
    slug: 'zla-zla',
    featuredImage: '/our-work/zla-zla-our-work.jpg',
    listImage: '/our-work/zla-zla-home.jpg',
    categories: ['branding', 'social media', 'marketing'],
    backgroundColor: '#000',
    textColor: '#fff',
    ready: true,
  },
  {
    title: 'Bistro grad',
    slug: 'bistro-grad',
    featuredImage: '/our-work/bistro-grad-our-work.png',
    listImage: '/our-work/bistro-grad-home.png',
    categories: ['social media', 'marketing'],
    backgroundColor: '#F286B7',
    textColor: '#000',
    ready: true,
  },
  {
    title: 'Prana',
    slug: 'prana',
    featuredImage: '/our-work/prana-our-work.png',
    listImage: '/our-work/prana-home.png',
    categories: ['branding', 'social media', 'marketing'],
    backgroundColor: '#FFF7EC',
    textColor: '#000',
    ready: true,
  },
  // {
  //   title: 'Roger Directors Agency',
  //   slug: 'roger-directors',
  //   featuredImage: '/our-work/roger-our-work.png',
  //   listImage: '/our-work/roger-home.png',
  //   categories: ['development'],
  //   backgroundColor: '#8eb8a3',
  //   textColor: '#000',
  //   ready: false,
  // },
  {
    title: 'ZLA ZLA',
    slug: 'zla-zla',
    featuredImage: '/our-work/zla-zla-our-work.jpg',
    listImage: '/our-work/zla-zla-home.jpg',
    categories: ['branding', 'social media', 'marketing'],
    backgroundColor: '#000',
    textColor: '#fff',
    ready: true,
  },
  {
    title: 'Bistro grad',
    slug: 'bistro-grad',
    featuredImage: '/our-work/bistro-grad-our-work.png',
    listImage: '/our-work/bistro-grad-home.png',
    categories: ['social media', 'marketing'],
    backgroundColor: '#F286B7',
    textColor: '#000',
    ready: true,
  },
  {
    title: 'Prana',
    slug: 'prana',
    featuredImage: '/our-work/prana-our-work.png',
    listImage: '/our-work/prana-home.png',
    categories: ['branding', 'social media', 'marketing'],
    backgroundColor: '#FFF7EC',
    textColor: '#000',
    ready: true,
  },
  // {
  //   title: 'Roger Directors Agency',
  //   slug: 'roger-directors',
  //   featuredImage: '/our-work/roger-our-work.png',
  //   listImage: '/our-work/roger-home.png',
  //   categories: ['development'],
  //   backgroundColor: '#8eb8a3',
  //   textColor: '#000',
  //   ready: false,
  // },
  {
    title: 'ZLA ZLA',
    slug: 'zla-zla',
    featuredImage: '/our-work/zla-zla-our-work.jpg',
    listImage: '/our-work/zla-zla-home.jpg',
    categories: ['branding', 'social media', 'marketing'],
    backgroundColor: '#000',
    textColor: '#fff',
    ready: true,
  },
  {
    title: 'Bistro grad',
    slug: 'bistro-grad',
    featuredImage: '/our-work/bistro-grad-our-work.png',
    listImage: '/our-work/bistro-grad-home.png',
    categories: ['social media', 'marketing'],
    backgroundColor: '#F286B7',
    textColor: '#000',
    ready: true,
  },
  {
    title: 'Prana',
    slug: 'prana',
    featuredImage: '/our-work/prana-our-work.png',
    listImage: '/our-work/prana-home.png',
    categories: ['branding', 'social media', 'marketing'],
    backgroundColor: '#FFF7EC',
    textColor: '#000',
    ready: true,
  },
  // {
  //   title: 'Roger Directors Agency',
  //   slug: 'roger-directors',
  //   featuredImage: '/our-work/roger-our-work.png',
  //   listImage: '/our-work/roger-home.png',
  //   categories: ['development'],
  //   backgroundColor: '#8eb8a3',
  //   textColor: '#000',
  //   ready: false,
  // },
  {
    title: 'ZLA ZLA',
    slug: 'zla-zla',
    featuredImage: '/our-work/zla-zla-our-work.jpg',
    listImage: '/our-work/zla-zla-home.jpg',
    categories: ['branding', 'social media', 'marketing'],
    backgroundColor: '#000',
    textColor: '#fff',
    ready: true,
  },
];

export const team = [
  {
    listImage: '/team/darja-babovic.jpeg',
    subtitle: 'the founder',
    title: 'Darja Babović',
    hoverColor: '#ff3358ff',
  },
  {
    listImage: '/team/tara-dinic.jpg',
    subtitle: 'the smart one',
    title: 'Tara Dinić',
    hoverColor: '#dc6acfff',
  },
  {
    listImage: '/team/andjela-zivic.jpeg',
    subtitle: 'the good one',
    title: 'Anđela Živić',
    hoverColor: '#ffd600ff',
  },
  {
    listImage: '/team/jelena-ristic.jpg',
    subtitle: 'the creative one',
    title: 'Jelena Ristić',
    hoverColor: '#9cfffaff',
  },
  {
    listImage: '/team/djordje-cetkovic.jpg',
    subtitle: 'the artistic one',
    title: 'Đorđe Ćetković',
    hoverColor: '#d2fdffff',
  },
  {
    listImage: '/team/igor-stanisavljevic.jpg',
    subtitle: 'the techy one',
    title: 'Igor Stanisavljević',
    hoverColor: '#ff3358ff',
  },
  {
    listImage: '/team/dea-krzelj.jpeg',
    subtitle: 'the underground one',
    title: 'Dea Krželj',
    hoverColor: '#dc6acfff',
  },
  {
    listImage: '/team/andja-nikolic.jpg',
    subtitle: 'the detail-oriented one',
    title: 'Anđa Nikolić',
    hoverColor: '#ffd600ff',
  },
  {
    listImage: '/team/tea-vukadin.jpg',
    subtitle: 'the one who does it all',
    title: 'Tea Vukadin',
    hoverColor: '#9cfffaff',
  },
];

export const socials = [
  {
    link: 'https://www.instagram.com/beehivebelgrade',
    text: 'Instagram',
  },
  {
    link: 'https://www.linkedin.com/company/beehive-digital-creative/',
    text: 'LinkedIn',
  },
];

export const coreValues = [
  {
    title: 'respect',
    icon: '/coreValues/core-value-icon-1.svg',
    number: '01',
  },
  {
    title: 'trust',
    icon: '/coreValues/core-value-icon-2.svg',
    number: '02',
  },
  {
    title: 'curiosity',
    icon: '/coreValues/core-value-icon-3.svg',
    number: '03',
  },
  {
    title: 'freedom',
    icon: '/coreValues/core-value-icon-4.svg',
    number: '04',
  },
];
